function Employee({employeeid,lastname, firstname, middlename, email, title, department, salary, account, phonenumber, status, leave, key}){
    return(
        <>
                <td>
                    {employeeid}
                </td>
                <td>
                    {lastname}
                </td>
                <td>
                    {firstname}
                </td>
                <td>
                    {middlename}
                </td>
                <td>
                    {phonenumber}
                </td>
                <td>
                    {email}
                </td>
                <td>
                    {title}
                </td>
                <td>
                    {department}
                </td>
                <td>
                    {status}
                </td>
                <td>
                    {salary}
                </td>
                <td>
                    {leave}
                </td>
                <td>
                    {account}
                </td>
        </>
    )
}

export default Employee